# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'SDWebImage', '~> 4.0.0'

target 'OC_VS_JS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OC_VS_JS

end
